#141404651 Game invite and user limit
andela/kakashi-cfh pull request #14
Opened 2017-03-29 18:47 UTC by Andela-JUdensi

#### What does this PR do?
Implements the game invite and game user limit requirements.

#### Description of Task to be completed?
1. Limit users to send send invites to at most 11 people other than themselves.
2. Limit the maximum players for each game to 12 people and a minimum of 3.
3. Pop up to inform users of activity.
4. An authenticated endpoint to search current users.

#### How should this be manually tested?
N/A

#### Any background context you want to provide?
To test the send invite funtionality, a gmail address with the pass word should be added as environmental variables in this format:
GMAIL_ADDRR= 
GMAIL_PASSWORD=

#### What are the relevant pivotal tracker stories?
Users should be able to send invites to at most 11 people other than themselves (#141404651)

#### Screenshots (if appropriate)
N/A

#### Questions:
N/A

2017-04-06 15:28 UTC, sdowoade commented on .eslintrc.json
> +    "no-use-before-define": 0,
We should avoid changing this file. The rules are set for a reason.

2017-04-06 15:28 UTC, sdowoade commented on app/controllers/index.js
> +// const mongoose = require('mongoose');
We can remove this if it's not being used. Comments should always be explanatory.

2017-04-06 16:02 UTC, Andela-JUdensi commented on .eslintrc.json
> +    "no-use-before-define": 0,
Okay. Noted

2017-04-06 17:31 UTC, andela-dowoade commented on .env
> +MONGOHQ_URL= mongodb://127.0.0.1:27017/kakashi
This should not be in here.

2017-04-06 19:11 UTC, sdowoade requested changes

2017-04-06 19:11 UTC, andela-dowoade commented on bower_components/angular-bootstrap/.bower.json
> +  "author": {
Let's avoid pushing generated modules. This folder should not be here.

2017-04-07 10:44 UTC, sdowoade approved these changes

2017-04-07 10:49 UTC, merged