Chore/141404643/convert from grunt to gulp
andela/kakashi-cfh pull request #8
Opened 2017-03-14 11:55 UTC by Andela-JUdensi

What does this PR do?

Convert grunt to gulp task runner

Description of Task to be completed?

Livereload of development files (.js, .css, .scss, .html)
Linting using Eslint
Server start and server reload
How should this be manually tested?

Run 'gulp' on the terminal:

starts sever
performs browser reload on file changes
performs server reload on file changes
Run 'gulp lint' on the terminal
tests syntax adherence to airbnb
Any background context you want to provide?

N/A

What are the relevant pivotal tracker stories?

Convert from Grunt to Gulp task runner (#141404643)

Screenshots (if appropriate)

N/A

Questions:

N/A

2017-03-14 15:09 UTC, sdowoade requested changes

2017-03-14 15:09 UTC, andela-dowoade commented on package.json
> +    "grunt": "^1.0.1",
Do we still need grunt?

2017-03-14 15:16 UTC, sdowoade requested changes

2017-03-14 15:16 UTC, andela-dowoade commented on package.json
> +    "test": "",
Looks like we are going to need a task for running tests.

2017-03-14 15:37 UTC, Andela-JUdensi commented on package.json
> +    "test": "",
Okay. Working on that

2017-03-16 12:20 UTC, sdowoade requested changes

2017-03-16 12:20 UTC, sdowoade commented on .env
> +PORT= 3000
This shouldn't be in here.

2017-03-16 12:20 UTC, sdowoade commented on test/backend/backendSpec.js
> +const jasmine = require('jasmine');
I don't think this is required. It's not being used.

2017-03-16 12:20 UTC, sdowoade commented on package.json
> +    "gulp-mocha": "^4.1.0",
Are we using mocha or jasmine?

2017-03-16 12:20 UTC, sdowoade commented on .travis.yml
> +  - "6"
Don't understand this change. Can you clarify?

2017-03-16 19:15 UTC, sdowoade requested changes

2017-03-16 19:15 UTC, andela-dowoade commented on coverage/Chrome 57.0.2987 (Mac OS X 10.12.3)/lcov-report/base.css
> +body, html {
The coverage folder is auto-generated after tests are run. This shouldn't be included in the repo. Please add `coverage` to the `.gitignore` file. 

You can revert the commit that included this.

2017-03-20 09:48 UTC, sdowoade approved these changes

2017-03-20 10:46 UTC, merged